# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN pip3 install requests bs4 
# psycopg2


# Command to run the Python script (adjust this based on your script name)
CMD ["python3", "webnews_scrapper.py"]
CMD ["python3", "bbcnews_scrapper.py"]
CMD ["python3", "theguardian_scrapper.py"]